import { Injectable } from '@angular/core';
import { Projet } from 'src/app/interfaces/projet';
@Injectable({
  providedIn: 'root'
})
export class DonneesService {
  articles: Array<Projet> = [
    {
      id: 1,
      icon: "fab fa-react fa-4x",
      outils: "React-native, Python, Flask, Bootstrap, Node.js, MySql, Postman, AWS. (Lead Développeur)" ,
      nomIcon: "REACT-NATIVE",
      imageJombo: "https://images.unsplash.com/photo-1498050108023-c5249f4df085?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Nnx8ZGV2ZWxvcGVyfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      titre: "Concevoir nativement des interfaces utilisateurs",
      resume:"Rendre l'expérience utilisateur agréable via les composants natifs de votre mobile en présentant une ergonomie attractive, une navigation simple et intuitive",
      premier: "Développement des interfaces responsives avec react-native pour différentes étapes de spécification",
      deux: "Déploiement de la plate-forme sur AWS",
      trois: "Configuration du pipeline ci/cd",
      quatre: "Mise en place du routing / routing dynamique",
      cinq: "Configuration de webpack",
      six: "Amélioration du référencement du site vitrine en se basant sur Lighthouse",
      sept: "Optimisation des performances du site",
      huit: "Optimisation de l’accessibilité",
      neuf: "Mise en place du PWA",
      dix: "Ajout de nouvelles features demandées par les clients",
      onze: "Correction de bugs",
      douze: "Optimisation du code (refactoring) et remplacement du code « deprecated »",
      treize: "Mise à jour de différentes librairies JS",
      quatorze: "Déploiement de deux serveurs pour gérer les ressources",
      quinze: "Formation des stagiaires de master pour leur monter en compétences",
    },
    {
      id: 2,
      icon: "fab fa-react fa-4x",
      outils: "React,Bootstrap, Express, Node.js, MySql, Postman",
      nomIcon: "REACT",
      titre: "Concevoir des interfaces utilisateurs",
      resume:"Rendre l'expérience utilisateur agréable sur votre site en présentant une ergonomie attractive de votre site et une navigation simple",
      premier: "Définir une architecture technique adaptée au besoin",
      deux: "Définir l’ergonomie et l’UX Design d’une application",
      trois: "Conseiller et valider la solution avec le client",
      quatre: "Concevoir des interfaces graphiques avec HTML5, CSS3",
      cinq: "Dynamiser des pages web avec React, typeScript et Bootstrap",
      six: "Concevoir des architectures d'applications avec UML",
      sept: "Organiser et gérer son code source pour favoriser le travail en équipe",
      huit: "Construire le site e-commerce avec React",
      neuf: "Développer des web services avec node.js",
      dix: "Maintenir et faire évoluer des applications",
    },
    {
      id: 3,
      icon: "fab fa-python fa-4x",
      outils: "Linux, Windows, VirtualBox, Python, Kubernetes, Terraform, Jenkins, Gitlab-ci, Ansible",
      nomIcon: "CONSULTANT DevOps",
      titre: "Mise en oeuvre du CI/CD, assurer l'administration des applications dans le cloud",
      resume: "Définir des processus d'intégration et de déploiement efficaces qui garantissent la haute disponibilité des applications",
      premier: "Mise en place de la méthodologie agile de type Scrum",
      deux: "Mise en place des environnements de tests",
      trois:  "Migration des applications python/Django on-premise vers GCP",
      quatre: " Mettre en place des pipelines CI/CD avec Cloudrun, Cloudbuild et App Engine",
      cinq: " Sécuriser les données via les secrets et buckets",
      six: "Optimiser le déploiement des images docker",
      sept: "Minimiser le coût de consommation des ressources de déploiement sur GCP",
      huit: "Déployer des serveurs dans le cloud AWS",
      neuf: "Configurer et déployer une chaine d’intégration continue avec Jenkins et Gitlab-ci",
      dix: "Déploiement d’une infrastructure dans le cloud AWS avec terraform, kubernetes",
      onze: "Assurer l’administration des applications",
      douze: "Assurer les mises à jour et les évolutions techniques",
    },
    {
      id: 4,
      icon: "fab fa-angular fa-4x",
      outils: "Angular,Bootstrap, Express, Node.js, MySql, Postman",
      nomIcon: "ANGULAR",
      titre: "Creation d'un site e-commerce",
      resume:"Créer un site de vente de livres en ligne pour Ib Groupe Cegos, spécialisé dans la vente de livres de formation. Son magasin est situé à Paris",
      premier: " Définir une architecture technique adaptée au besoin",
      deux: "Définir l’ergonomie et l’UX Design d’une application",
      trois: "Conseiller et valider la solution avec le client",
      quatre: "Concevoir des interfaces graphiques avec HTML5, CSS3",
      cinq: "Dynamiser des pages web avec Angular, typeScript et Bootstrap",
      six: "Concevoir des architectures d'applications avec UML",
      sept: "Organiser et gérer son code source pour favoriser le travail en équipe",
      huit: "Construire le site e-commerce de Ib-Groupe CEGOS avec Angular",
      neuf: "Développer des web services avec node.js",
      dix: "Maintenir et faire évoluer des applications",

    },
    {
      id: 5,
      icon: "fab fa-vuejs fa-4x",
      outils: "Vue.js, Bootstrap, Express, Node.js, MongoDB, Postman",
      nomIcon: "VUEJS",
      titre: "Creation d'un réseau social d'entreprise",
      resume:"Créer un réseau social permettant d'échanger avec les personnels afin de comprendre leurs satisfactions sur l'ambiance du travail",
      premier: "Définir une architecture technique adaptée au besoin",
      deux: "Définir l’ergonomie et l’UX Design d’une application",
      trois: "Conseiller et valider la solution avec le client",
      quatre: "Concevoir des interfaces graphiques avec HTML5, CSS3",
      cinq: "Dynamiser des pages web avec Vue.js et Bootstrap",
      six: "Concevoir des architectures d'applications avec UML",
      sept: "Organiser et gérer son code source pour favoriser le travail en équipe",
      huit: "Construire l'API sécurisée respectant le RGPD et les opérations de l'OWASP",
      neuf: "Développer des web services avec node.js",
      dix: "Utiliser la couche expressJs sur node.js",
    },
    {
      id: 6,
      icon: "",
      outils: "Python, R, Scikit-learn, Matplotlib, Pandas, seaborn",
      imageUrl: "https://images.unsplash.com/photo-1551288049-bebda4e38f71?ixid=MnwxMjA3fDB8MHxzZWFyY2h8M3x8ZGF0YSUyMHNjaWVuY2V8ZW58MHx8MHx8&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      titre: "Etude et analyse de données au CNRS",
      resume:"Analyser les données au CNRS pour comprendre leurs évolutions et leur donner du sens",
      premier: "Analyse statistique de données avec python",
      deux: "Effectuer une statistique descriptive avec python",
      trois: "Apprentissage supervisé (corrélation entre les données) avec Python : Scikit-learn, R",
      quatre: "Apprentissage non supervisé avec Python : Scikit-learn, R",
      cinq: "Optimisation des modèles via GridSearchCV ",
      six: "Créer des métriques spécifiques ",
      sept: "Modèles statistiques et visualisation de l'information via Python (Scikit-learn, Matplotlib, Pandas, seaborn)",
    },
    {
      id: 7,
      icon: "fab fa-symfony fa-4x",
      outils: "PHP, Symfony, MySql, IPiPlatForm, Bootstrap",
      nomIcon: "PHP-SYMFONY",
      imageUrl: "",
      titre: "Construire l'application pinterest",
      resume:"Développer une application qui affiche les objets pinterests en vente, en se basant sur l'un des frameWorks php complet très utilisé, qui est Symfony",
      premier: "Définir une architecture technique adaptée au besoin",
      deux: "Définir l’ergonomie et l’UX Design d’une application",
      trois: "Concevoir des interfaces graphiques avec twig",
      quatre: "Dynamiser des pages web avec PHP et Bootstrap",
      cinq: "Concevoir des architectures d'applications avec UML",
      six: "Organiser et gérer son code source pour favoriser le travail en équipe",
      sept: "Construire le site complet affichant les pins",
      huit: "Développer des web services avec APiPlatForm",
    },
     {
      id: 8,
      icon: "",
      outils: "Google search console, GTmetrix, Google Analytics",
      nomIcon: "",
      imageUrl: "https://images.unsplash.com/photo-1560472354-b33ff0c44a43?ixid=MnwxMjA3fDB8MHxzZWFyY2h8Mnx8c2VvfGVufDB8fDB8fA%3D%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=500&q=60",
      imageSeo: "seo",
      titre: "Optimiser un site web existant",
      resume:"Référencement SEO du site la chouette agence pour favoriser l'accessibilité aux utilisateurs et aux robots Google",
      premier: "Le principe mobile friendly a été respecté lors de l’optimisation du site web",
      deux: "Respecter le niveau AA de WCAG 2.0",
      trois: "Développer un code qui respecte la norme W3C",
      quatre: "Faciliter le crawlabilité et l'indexabilité du site existant",
      cinq: "Rechercher les mots-clés pertinents à l'aide l'outil Keyword planner de Google Ads",
      six: "Rédiger un contenu texte riche et pertinent",
      sept: "Respecter l'hiérarchisation des balises html",
      huit: "Rendre le site responsive",
    }
  ]
 
  constructor() { }

  getAll(){
    return this.articles;
  }
  getOneById(id: number) {
    const element = this.articles.find(elt=>elt.id === id);
    return element; 
  }

}
